# Generated by Django 3.2.5 on 2022-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_url', models.FileField(upload_to='movies')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
